fix: Add KeyboardState to AttachmentsEditor to prevent crash in signature mode
Fixes crash when dismissing keyboard via gesture in signature input view by
providing the missing KeyboardState environment object.

Crashlytic Log:
SwiftUICore/EnvironmentObject.swift:92: Fatal error: No ObservableObject of type KeyboardState found.
A View.environmentObject(_:) for KeyboardState may be missing as an ancestor of this view.